# Generated by Django 5.1 on 2024-12-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_skill_application_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="skills",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="application",
            name="skills",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
