# Generated by Django 5.1 on 2024-12-06 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_remove_application_skills_delete_skill_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_percentage", models.FloatField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.application",
                    ),
                ),
            ],
        ),
    ]
